# Generated by Django 6.0.1 on 2026-01-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
    ]
