# Generated by Django 6.0.1 on 2026-02-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_seed_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.JSONField(),
        ),
    ]
