# Generated by Django 6.0.1 on 2026-02-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(help_text='Comma separated skills'),
        ),
    ]
