# Generated by Django 6.0.1 on 2026-02-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='backlogs',
            field=models.IntegerField(),
        ),
    ]
