# Generated by Django 6.0.1 on 2026-02-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_backlogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file',
        ),
    ]
